feat: integrate wda workflow in the pipeline

diff --git a/.github/workflows/launch_tests.yml b/.github/workflows/launch_tests.yml
--- a/.github/workflows/launch_tests.yml
+++ b/.github/workflows/launch_tests.yml
@@ -6,6 +6,11 @@ on:
       artifact_app:
         description: 'Name of the .app artifact to test'
         type: string
+        required: true
+      wda:
+        description: 'Name of WDA artifact'
+        type: string
+        required: true
     secrets:
       OC_SERVER_URL:
         required: true  
@@ -14,6 +19,10 @@ jobs:
   tests:
     name: launch_tests
     runs-on: macos-15
+
+    env:
+        DEVICE: ${{ vars.DEFAULT_DEVICE }}
+        OS: ${{ vars.DEFAULT_OS }}
 
     steps:
       # Checkout repo 
@@ -26,6 +35,12 @@ jobs:
         with:
           name: ${{ inputs.artifact_app }}
           path: ./src/test/resources 
+
+      - name: Download WebDriverAgent artifact
+        uses: actions/download-artifact@v4
+        with:
+          name: ${{ inputs.wda }}
+          path: ./
 
       # List folders
       - name: List stuff
@@ -67,7 +82,7 @@ jobs:
           OS_VERSION="${{ vars.DEFAULT_OS }}"
 
           # Find the UDID of the desired simulator
-          UDID=$(xcrun simctl list devices "$OS_VERSION" \
+          UDID=$(xcrun simctl list devices "iOS $OS_VERSION" \
             | grep -E "^\s*$DEVICE \(" \
             | head -n 1 \
             | awk -F '[()]' '{print $2}')
@@ -80,18 +95,69 @@ jobs:
           # Check if the simulator is already booted
           STATE=$(xcrun simctl list devices | grep "$UDID" | awk -F'[()]' '{print $4}')
 
+          # Export UDID always
+          echo "UDID_DEVICE=$UDID" >> $GITHUB_ENV
+
           if [ "$STATE" = "Booted" ]; then
             echo "✅ Simulator '$DEVICE' ($OS_VERSION) is already running (UDID: $UDID)."
           else
             echo "🚀 Booting simulator '$DEVICE' ($OS_VERSION)..."
             xcrun simctl boot "$UDID"
             xcrun simctl bootstatus "$UDID" -b
-            echo "UDID_DEVICE=$UDID" >> $GITHUB_ENV
             echo "✅ Simulator is now ready."
           fi
 
           # Optionally, print the booted simulator list for debugging
           xcrun simctl list devices | grep Booted
+
+      - name: Unzip WDA
+        run: |
+          ls -al .
+          unzip -q "${{ inputs.wda }}" -d .
+          ls -al .
+
+      - name: Install and launch WebDriverAgent on simulator
+        run: |
+          echo "Searching for WebDriverAgent build inside downloaded artifact..."
+
+          ls -al .
+
+          # Find the precompiled WDA app
+          WDA_APP=$(find ./DerivedData -name "WebDriverAgentRunner-Runner.app" -type d | head -n 1)
+
+          if [ -z "$WDA_APP" ]; then
+            echo "ERROR: WebDriverAgentRunner-Runner.app not found inside artifact '${{ inputs.wda }}'"
+            exit 1
+          fi
+
+          echo "WDA app found at: $WDA_APP"
+
+          # Locate the booted simulator
+          echo "Resolving booted simulator UDID for $DEVICE (iOS $OS_VERSION)..."
+          SIM_ID="$UDID_DEVICE"
+
+          if [ -z "$SIM_ID" ]; then
+            echo "ERROR: No booted simulator matches: $DEVICE (iOS $OS_VERSION)"
+            xcrun simctl list
+            exit 1
+          fi
+
+          echo "Booted simulator detected: $SIM_ID"
+
+          # Install WebDriverAgent
+          echo "Installing WebDriverAgent..."
+          xcrun simctl install "$SIM_ID" "$WDA_APP"
+          echo "WDA installed successfully"
+
+          # Get bundle ID from WDA app
+          BUNDLE_ID=$(/usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" "$WDA_APP/Info.plist")
+          echo "Bundle Identifier: $BUNDLE_ID"
+
+          # Launch WebDriverAgent service
+          echo "Launching WebDriverAgent..."
+          xcrun simctl launch "$SIM_ID" "$BUNDLE_ID"
+
+          echo "WebDriverAgent is now running on the simulator"
 
       # Set up enviroment
       - name: Setup JDK
